### ISSUE TITLE
Add CI for linting and tests

### ISSUE THREAD

**Issue by jamestelfer** [sj26/aws-assume-role-with-web-identity-buildkite-plugin#14]
I'm curious how this works in the plug-in org. What would I need to do to kick this off? Or is it something that only Buildkiters can contribute?

**Comment by james2791** [comment]
@jamestelfer a great question - the short answer (and a thanks for the timing!) is that we're on the case for uplifting the CI for this plugin exclusively. At the moment only currently Buildkite staff can contribute towards it.

I'll close this for now with this action piece in progress 👍
