### ISSUE TITLE
document thumbprint_list

### ISSUE THREAD

**Issue by flokli** [sj26/aws-assume-role-with-web-identity-buildkite-plugin#2]
I'm trying to configure the AWS IAM OIDC provider via terraform, but I'm not sure what to configure in [`thumbprint_list`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_openid_connect_provider.html#thumbprint_list):

> - (Required) A list of server certificate thumbprints for the OpenID Connect (OIDC) identity provider's server certificate(s).

It seems AWS explicitly requires pinning some HTTPS certificates used for the JWKS endpoint here (but has some special rules for some websites):

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html says:

> AWS secures communication with some OIDC identity providers (IdPs) through our library of trusted certificate authorities (CAs) instead of using a certificate thumbprint to verify your IdP server certificate. These OIDC IdPs include Google, Auth0, and those that use an Amazon S3 bucket to host a JSON Web Key Set (JWKS) endpoint. In these cases, your legacy thumbprint remains in your configuration, but is no longer used for validation.

It's not entirely clear if Buildkite is part of that list - in any case, a little terraform example would be helpful :-)

**Comment by flokli** [comment]
Following https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html, the fingerprint I came up with was `9E99A48A9960B14926BB7F3B02E22DA2B0AB7280`, but I wanted to make sure it's the right one, and won't suddenly change if you switch certificate providers.

**Comment by sj26** [comment]
Yes, `9E99A48A9960B14926BB7F3B02E22DA2B0AB7280` is correct. Buildkite is hosted on AWS, and we use AWS Certificate Manager to provision our certificates automatically from AWS' Certificate Authority. That fingerprint corresponds to Starfield's root CA, used by Amazon.

That CA cert lasts until 2034. It should remain stable, even if our leaf certificate is automatically rotated.

But you're right, it would change if we needed to switch where our certs are generated. We have no plans to do so, but if we need to change root certificate authorities then reasonable notice will be provided.

I don't think we should document this literal fingerprint. It feels too much like a magic number, and could get lost if we did need to change providers, however unlikely. But automating this via terraform would be a good idea, and including an example in the docs would also be nice. I'll see what we can do.

**Comment by sj26** [comment]
There's an example for configuring an OIDC provider for EKS here which feels similar:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster.html#enabling-iam-roles-for-service-accounts

So something like this should work -- the terraform docs say that [the root of the chain comes first](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/data-sources/certificate#certificates), and it's still safe because it will [verify the chain by default](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/data-sources/certificate#verify_chain):

```terraform
locals {
  agent_endpoint = "https://agent.buildkite.com"
}

data "tls_certificate" "buildkite-agent" {
  url = locals.agent_endpoint
}

resource "aws_iam_openid_connect_provider" "buildkite-agent" {
  url = locals.agent_endpoint

  client_id_list = [
    "sts.amazonaws.com",
  ]

  thumbprint_list = [
    data.tls_certificate.buildkite-agent.certificates[0].sha1_fingerprint,
  ]
}
```

I've updated our own internal configuration to match the above and it was a clean terraform plan.

**Comment by sj26** [comment]
I've added the above example into the docs, too.

Thanks for the questions, and suggestion!
